### ISSUE TITLE
"pip install --upgrade msl-package-manager" fails on Windows

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/msl-package-manager#2]
Upgrading on Windows fails if the version of pip is not the latest because pip tries to upgrade itself while it is being executed.

**Options:**
1. Use the `--no-deps` flag
2. Remove pip from *install_requires* because this is a circular dependency (should `setuptools` and `colorama` also be upgraded?)
3. Allow the `msl-package-manager` to upgrade itself

```
D:\code>msl list
Inspecting packages in c:\users\jborbely\miniconda3\envs\bug

MSL Package         Version Description
------------------- ------- --------------------------------------------------------
msl-package-manager 1.5.0   Install, uninstall, update, list and create MSL packages

D:\code>pip install --upgrade msl-package-manager
Collecting msl-package-manager
  Using cached https://files.pythonhosted.org/packages/a6/e2/a369fb543e84198b5c27134d87bb5866f0efe857dcf7e832d1fe1fddd393/msl_package_manager-2.0.0-py2.py3-none-any.whl
Requirement already up-to-date: colorama in c:\users\jborbely\miniconda3\envs\bug\lib\site-packages (from msl-package-manager)
Collecting setuptools (from msl-package-manager)
  Downloading https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl (567kB)
    100% |################################| 573kB 3.4MB/s
Collecting pip (from msl-package-manager)
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: setuptools, pip, msl-package-manager
  Found existing installation: setuptools 38.4.0
    Uninstalling setuptools-38.4.0:
      Successfully uninstalled setuptools-38.4.0
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Exception:
Traceback (most recent call last):
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\basecommand.py", line 215, in main
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\commands\install.py", line 342, in run
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\req\req_set.py", line 795, in install
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 261, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\shutil.py", line 266, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\jborbely\Miniconda3\envs\bug\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
WindowsError: [Error 5] Access is denied: 'c:\\users\\jborbely\\appdata\\local\\temp\\pip-0jumuv-uninstall\\users\\jborbely\\miniconda3\\envs\\bug\\scripts\\pip.exe'
```

**Comment by jborbely** [comment]
fixed in v2.1.0
